site_name: SportLudique Project 2024-2025
site_url: https://lmeryfulbert.github.io/SportLudique2024-2025/
theme:
  name: material
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#plugins:
#  - social
