site_name: SportLudique Project 2024-2025
site_url: https://lmeryfulbert.github.io/SportLudique2024-2025/
theme:
  name: material
  palette:
    - scheme: slate
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/brightness-4'
        name: 'Switch to light mode'
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: 'material/brightness-7'
        name: 'Switch to dark mode'
  #features:
  #  - navigation.tabs
  #  - navigation.top
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
#plugins:
#  - social
